### PR TITLE
Actions identification in replies

### PR DESCRIPTION
**Pull request by muxx**
I introduced `id` attribute for actions which will returned with replies. New attribute allows to relate replies to actions.

### CODE REVIEW

**Comment by YuriyNasretdinov** [comment]
Why do you need to introduce this field? You can only execute one request at a time and you must wait until you get "FinalReply" before sending new requests.

**Comment by muxx** [comment]
I want use GoSSHa in the same mode as pssh when I generate the actions list and execute it. At the end of execution I collect information about results and should relate replies with actions. Else it is hard if some actions contain syntax errors thats why excluded from execution list and not returned common replies.

**Comment by YuriyNasretdinov** [comment]
Could you please specify which pssh you mean?

чт, 29 дек. 2016 г. в 19:33, Ilyas Salikhov <notifications@github.com>:

**Comment by muxx** [comment]
This one:
https://github.com/badoo/libpssh
https://github.com/badoo/pssh_extension

We are using it for deploing and want to migrate to GoSSHa.

**Comment by YuriyNasretdinov** [comment]
There is no concept of "task lists" in GoSSHa. The "id" for each reply is
just hostname. You cannot send new requests until previous one has finishes
so I still don't understand why you need this.

чт, 29 дек. 2016 г. в 19:39, Ilyas Salikhov <notifications@github.com>:

**Comment by muxx** [comment]
May be do you have examples of right calling of the GoSSHa from PHP in case of several actions?

**Comment by YuriyNasretdinov** [comment]
GoSSHa does not support execution of several actions in parallel. You need
to start several GoSSHa processes if you want to do so.
Le jeu. 29 déc. 2016 à 19:47, Ilyas Salikhov <notifications@github.com> a
écrit :

**Comment by muxx** [comment]
I mean several actions by turns. But ok, I understood GoSSHa priciples and revoke my pull request.

Thanks for explanation and happy new year! :)

**Comment by muxx** [comment]
Made php client for GoSSHa https://github.com/muxx/dplr + added parallel executing different tasks when several GoSSHa instances run.

**Pull request closed without merging**
